kind: Pod
apiVersion: v1
metadata:
  name: iscsi-block-node1
  namespace: infinidat-csi
  labels:
    security: s1
spec:
  containers:
    - name: csitest
      image: $_E2E_TEST_BLOCK_IMAGE
      volumeMounts:
      command: [ "csitestimageblock" ]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: iscsi-block-pvc-rwx
