apiVersion: csidriver.infinidat.com/v1
kind: Iboxcg
metadata:
  annotations:
    infinidat.com/secret_name: infinibox-creds
    infinidat.com/secret_namespace: infinidat-csi
  name: iboxcg-remove-test
spec:
  description: "test remove member to cg"  # user defined description
  local_cg_name: "non-replica-cg"
  local_volume_name: csi-test-03bd9a9b67
  base_action: "REMOVE"                    # valid values: ADD, REMOVE
