apiVersion: csidriver.infinidat.com/v1
kind: Iboxcg
metadata:
  annotations:
    infinidat.com/secret_name: infinibox-creds
    infinidat.com/secret_namespace: infinidat-csi
  name: iboxcg-add-test
spec:
  description: "test add member to cg"  # user defined description
  local_cg_name: $_E2E_IBOXREPLICA_CG
  local_volume_name: csi-test-553c258313
  base_action: "ADD"                    # valid values: ADD, REMOVE
