apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ibox-pvc-clone-snapshot-demo
  namespace: infinidat-csi
spec:
  volumeSnapshotClassName: ibox-snapshotclass-demo
  source:
    persistentVolumeClaimName: ibox-pvc-clone-demo

