apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ibox-pvc-clone-snapshot-demo
  namespace: infi
spec:
  snapshotClassName: ibox-snapshotclass-demo
  source:
    persistentVolumeClaimName: ibox-pvc-clone-demo

