apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: infinibox-csi-driver
  name: csi-1c1324de94
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  csi:
    controllerExpandSecretRef:
      name: infinibox-creds
      namespace: infi
    controllerPublishSecretRef:
      name: infinibox-creds
      namespace: infi
    driver: infinibox-csi-driver
    nodePublishSecretRef:
      name: infinibox-creds
      namespace: infi
    nodeStageSecretRef:
      name: infinibox-creds
      namespace: infi
    volumeAttributes:
      exportID: 3000
      ipAddress: 172.17.35.45
      storage_protocol: nfs
      # uid: 1000
      # gid: 1000
      # unix_permissions: 777
      volPathd: /csi-1c1324de94
    volumeHandle: 7394$$nfs
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ibox-nfs-storageclass-demo
  volumeMode: Filesystem
  mountOptions:
    - hard
    - rsize=1048576
    - wsize=1048576
