apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-restore-from-snapshot
  namespace: $_E2E_NAMESPACE
spec:
  storageClassName: $TEST_NAME
  dataSource:
    name: $TEST_NAME
    kind: VolumeSnapshot
    apiGroup: "snapshot.storage.k8s.io"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

