apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nfs-snapshot-locking
  namespace: $_E2E_NAMESPACE
spec:
  volumeSnapshotClassName: ibox-snapshotclass-locking
  source:
    persistentVolumeClaimName: nfs-pvc
