apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-existing-pv
  namespace: infi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-treeq-storageclass-demo-retain
  volumeName: csi-bf4d7e4f43
