apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sticky-treeq-pv
  namespace: infi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-treeq-storageclass-demo-retain
