---
# Source: https://github.com/kubernetes-csi/external-snapshotter/blob/release-4.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
#
# RBAC file for the snapshot controller.
#
# The snapshot controller implements the control loop for CSI snapshot functionality.
# It should be installed as part of the base Kubernetes distribution in an appropriate
# namespace for components implementing base system functionality. For installing with
# Vanilla Kubernetes, kube-system makes sense for the namespace.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-snapshot-controller
  namespace: {{ .Release.Namespace }}

