apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-ip-range-pvc
  namespace: $_E2E_NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-nfs-ip-range
  # volumeName: <<pv name>> #need to uncomment if want to use an existing pv
