apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc-rox-readers
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-iscsi-rox-readers
  volumeName: rox-pv-from-existing
