apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc-rox
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-iscsi-rox
  #volumeName: ocp413-a13ff923f6
