apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: infinidat-csi-metrics
  name: infinidat-csi-metrics
  namespace: infinidat-csi
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
  selector:
    matchLabels:
      app: infinidat-csi-metrics
