variables:
    MAINTENANCE_MODE: 1

stages:
    - test

default:
    image: quay.io/projectquay/golang:1.18

    before_script:
        - echo ${CI_PROJECT_DIR}

unit_tests:
    stage: test
    # dependencies:
    script:
        - make build
        - make test
