apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ibox-pvc-clone-demo
    namespace: infi
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ibox-iscsi-storageclass-demo
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: ibox-pvc-demo
