apiVersion: v1
kind: Secret
metadata:
  name: infinibox-iscsi-secret
  namespace: infi
type: Opaque
data:
  # set username to the base64 encoded user
  username: "{{ .Values.Infinibox.username | b64enc }}"
  # set password to the base64 encoded password
  password: "{{ .Values.Infinibox.password | b64enc }}"
  # set apiurl to the base64 encoded apihost
  hostip: "{{ .Values.Infinibox.apihost | b64enc }}"
