apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-iscsi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: infiniboxcsidriver-iscsi
