# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ibox-pvc-raw-demo
# spec:
#   volumeMode: Block
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: ibox-iscsi-storageclass-demo

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibox-iscsi-storageclass-demo