apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: infiniboxcsidriver-iscsi
provisioner: infinibox-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  storage_protocol: iscsi
  storagepool: iscsipool
  csi.storage.k8s.io/node-publish-secret-name: infinibox-iscsi-secret
  csi.storage.k8s.io/node-publish-secret-namespace: infi
  csi.storage.k8s.io/fstype: ext4
  targetPortal: 172.17.35.71
  iscsiInterface: "default"
  readOnly: "false"
  chapAuthDiscovery: "false"
  chapAuthSession: "false"
  networkspace: "niscsi"
