apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-pvc-clone-anno
    namespace: infinidat-csi
    annotations:
      # the following annotations have to match the values in pvc.yaml
      infinidat.com/pool_name: csitesting
      infinidat.com/network_space: NAS
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ibox-nfs-anno
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: nfs-pvc-anno
