apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-anno
  namespace: infinidat-csi
  annotations:
    infinidat.com/pool_name: csitesting
    infinidat.com/network_space: $_E2E_NETWORK_SPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-nfs-anno
  # volumeName: <<pv name>> #need to uncomment if want to use an existing pv
