apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibox-treeq-storageclass-demo
provisioner: infinibox-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - hard
  - rsize=1048576
  - wsize=1048576
parameters: 
  # reference secret with InfiniBox credentials
  csi.storage.k8s.io/controller-expand-secret-name: ${pvc.annotations['infinidat.com/ibox_secret']}
  csi.storage.k8s.io/controller-expand-secret-namespace: infinidat-csi
  csi.storage.k8s.io/controller-publish-secret-name: ${pvc.annotations['infinidat.com/ibox_secret']}
  csi.storage.k8s.io/controller-publish-secret-namespace: infinidat-csi
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.annotations['infinidat.com/ibox_secret']}
  csi.storage.k8s.io/node-publish-secret-namespace: infinidat-csi
  csi.storage.k8s.io/node-stage-secret-name: ${pvc.annotations['infinidat.com/ibox_secret']}
  csi.storage.k8s.io/node-stage-secret-namespace: infinidat-csi
  csi.storage.k8s.io/node-expand-secret-name: ${pvc.annotations['infinidat.com/ibox_secret']}
  csi.storage.k8s.io/node-expand-secret-namespace: infinidat-csi
  #  NOTE:  the following 2 csi parameters are commented out specifically to avoid errors in the external-provisioner
  #  on DeleteVolume() calls, the CSI driver instead removes the PV based on its pvc annotation logic
  #csi.storage.k8s.io/provisioner-secret-name: infinibox-creds
  #csi.storage.k8s.io/provisioner-secret-namespace: infinidat-csi

  pool_name: csitesting
  network_space: NAS
  #provision_type: THIN
  storage_protocol: nfs_treeq
  #fs_prefix: csit_
  #ssd_enabled: "true"
  # optional parameters
  uid: "3000"
  gid: "3000"
  # the following parameters can be used to override ibox limits
  # max_filesystems: "999"
  # max_treeqs_per_filesystem: "20"
  # max_filesystem_size: 30gib
  #
  # uncomment if you do not want to have the default export (e.g. node ip address) created
  # nfs_export_permissions : "[{'access':'RW','client':'192.168.147.190-192.168.147.199','no_root_squash':true}]" # ip address range example
  nfs_export_permissions : "[{'access':'RW','client':'*','no_root_squash':true}]" # wildcard example
