apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc-mutual-chap
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-iscsi-mutual-chap
  #volumeName: <<pv name>> #need to uncomment if want to existing pv
