apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: fc-snapshot-node-aff
  namespace: $_E2E_NAMESPACE
spec:
  volumeSnapshotClassName: ibox-snapshotclass
  source:
    persistentVolumeClaimName: fc-pvc-node-aff

