apiVersion: csidriver.infinidat.com/v1
kind: Iboxreplica
metadata:
  annotations:
    infinidat.com/secret_name: $_E2E_IBOX_SECRET
    infinidat.com/secret_namespace: $_E2E_NAMESPACE
  name: iboxreplica-aa-volume-sample
spec:
  is_preferred: true                        # set only for ACTIVE_ACTIVE, true = local system, false = the remote system
  description: "aa-volume-iboxreplica-test" # user defined description
  entity_type: "VOLUME"                     # valid values can be VOLUME or CG
  local_entity_name: $_E2E_IBOXREPLICA_VOLUME # this is the volume name to be replicated
  remote_entity_name: $_E2E_IBOXREPLICA_VOLUME # the target name to use
  replication_type: "ACTIVE_ACTIVE"         # valid values can be ACTIVE_ACTIVE or ASYNC
  link_remote_system_name: $_E2E_IBOXREPLICA_LINK_REMOTE_SYSTEM_NAME #the replication link name
  remote_pool_name: $_E2E_IBOXREPLICA_REMOTE_POOL_NAME        # the pool NAME on the remote ibox
  remote_ibox_credential_name: $_E2E_IBOXREPLICA_REMOTE_IBOX_SECRET_NAME
  remote_ibox_credential_namespace: $_E2E_IBOXREPLICA_REMOTE_IBOX_SECRET_NAMESPACE
