kind: Pod
apiVersion: v1
metadata:
  name: ibox-pod-treeq-demo
  namespace: infi
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/tmp/data"
        name: ibox-csi-volume
      command: [ "sleep", "1000" ]    
  volumes:
    - name: ibox-csi-volume
      persistentVolumeClaim:
        claimName: ibox-treeq-pvc-demo
