apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: treeq-pvc
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-treeq
