apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvme-pvc
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-nvme
  #volumeName: <<pv name>> #need to uncomment if want to existing pv
