apiVersion: v1
kind: Secret
metadata:
  name: iscsi-chap-creds
  namespace: {{ .Release.NameSpace }}
type: Opaque
data:
  node.session.auth.username: "{{ .Values.Chap.SessionAuthUsername | b64enc }}"
  node.session.auth.password: "{{ .Values.Chap.SessionAuthPassword | b64enc }}"
  node.session.auth.username_in: ""
  node.session.auth.password_in: ""
