apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: iscsi-pvc-clone
    namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ibox-iscsi
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: iscsi-pvc
