apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinibox-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: infinibox-operator
  template:
    metadata:
      labels:
        name: infinibox-operator
    spec:
      serviceAccountName: infinibox-operator
      containers:
        - name: infinibox-operator
          # Replace this with the built image name
          image: docker.io/nikhilbarge/infinibox-operator:v0.1
          imagePullPolicy: Always
          env:
            - name: "WATCH_NAMESPACE"
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "infinibox-operator"