kind: Pod
apiVersion: v1
metadata:
  name: treeq-test-fsg
  namespace: infinidat-csi
spec:
  securityContext:
    runAsUser: 3000
    runAsGroup: 3000
    fsGroup: 3000
  containers:
    - name: csitest
      image: $_E2E_TEST_IMAGE
      volumeMounts:
      - mountPath: "/tmp/csitesting"
        name: ibox-csi-volume
      command: [ "csitestimage" ]
  volumes:
    - name: ibox-csi-volume
      persistentVolumeClaim:
        claimName: treeq-pvc-fsg
