apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: treeq-pvc
  namespace: $_E2E_NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibox-treeq
