apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibox-iscsi-stress
provisioner: infinibox-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters: 
  csi.storage.k8s.io/provisioner-secret-name: $_E2E_IBOX_SECRET
  csi.storage.k8s.io/provisioner-secret-namespace: infinidat-csi
  csi.storage.k8s.io/controller-publish-secret-name: $_E2E_IBOX_SECRET
  csi.storage.k8s.io/controller-publish-secret-namespace: infinidat-csi
  csi.storage.k8s.io/node-stage-secret-name: $_E2E_IBOX_SECRET
  csi.storage.k8s.io/node-stage-secret-namespace: infinidat-csi
  csi.storage.k8s.io/node-publish-secret-name: $_E2E_IBOX_SECRET
  csi.storage.k8s.io/node-publish-secret-namespace: infinidat-csi
  csi.storage.k8s.io/controller-expand-secret-name: $_E2E_IBOX_SECRET
  csi.storage.k8s.io/controller-expand-secret-namespace: infinidat-csi
  csi.storage.k8s.io/node-expand-secret-name: $_E2E_IBOX_SECRET
  csi.storage.k8s.io/node-expand-secret-namespace: infinidat-csi
  csi.storage.k8s.io/fstype: ext4
  storage_protocol: iscsi
  network_space: "$_E2E_ISCSI_NETWORK_SPACE"
  pool_name: "$_E2E_POOL"
  useCHAP: "none" # none / chap / mutual_chap
  uid: "3000" # UID of volume
  gid: "3000" # GID of volume
  # unix_permissions: 777 # chmod -R of volume
