apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $TEST_NAME
  namespace: $_E2E_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: $TEST_NAME
