apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvme-pvc-fsg
  namespace: $_E2E_NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-nvme-fsg
  #volumeName: <<pv name>> #need to uncomment if want to existing pv
