apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: fc-pvc-clone-anno
    namespace: $_E2E_NAMESPACE
    annotations:
      # the following annotation has to match the one in pvc.yaml
      infinidat.com/pool_name: $_E2E_POOL
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ibox-fc-anno
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: fc-pvc-anno
