apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fc-pvc-anno
  namespace: $_E2E_NAMESPACE
  annotations:
    infinidat.com/pool_name: $_E2E_POOL
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-fc-anno
  #volumeName: <<pv name>> #need to uncomment if want to existing pv
