apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: fc-snapshot-anno
  namespace: infinidat-csi
spec:
  volumeSnapshotClassName: ibox-snapshotclass
  source:
    persistentVolumeClaimName: fc-pvc-anno

