apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-existing-pv
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-treeq-retain
  volumeName: csi-bf4d7e4f43
