apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc-volume-anno
  namespace: $_E2E_NAMESPACE
  annotations:
    infinidat.com/volume_metadata: "my-finance-application"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-iscsi-volume-anno
  #volumeName: <<pv name>> #need to uncomment if want to existing pv
