apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.accessKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secretAccessKey | b64enc | quote }}
  AWS_ENDPOINT_URL: {{ .Values.endpoint | b64enc | quote }}
