---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - csidriver.infinidat.com
  resources:
  - iboxreplicas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csidriver.infinidat.com
  resources:
  - iboxreplicas/finalizers
  verbs:
  - update
- apiGroups:
  - csidriver.infinidat.com
  resources:
  - iboxreplicas/status
  verbs:
  - get
  - patch
  - update
