apiVersion: v1
kind: Secret
metadata:
  name: ibox-s3-secret
  namespace: infinidat-csi
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "6p7THNecB7QnDwrOq4JJ"
  AWS_SECRET_ACCESS_KEY: "Bg7/CLzqvflFAUVdnrudHaylD+qFKQCM/WYYm7cD"
  AWS_ENDPOINT_URL: "http://172.20.38.142:9020"
