---
# vim: set filetype=yaml :
# Default values for infinibox-csi-driver.
# Values from this file are also used by
# operator-sdk when generating CSI operator
# bundle/manifests/infinibox-operator-certified.clusterserviceversion.yaml

replicaCount: 1

instanceCount: 1

# prefix for pv name
volumeNamePrefix: ibox

# log level of driver
logLevel: "info"

# name of the driver
# note same name will be used for provisioner name
csiDriverName: "infinibox-csi-driver"
csiDriverVersion: "2.11.0"

# set e2etesting to true if you want to expose the CSI socket (e.g. for e2e testing)
e2etesting: "false"

# set to true in order to strip off domain names from the host name that is registered on the ibox, this
# is useful if you have really long domain names which can exceed what the ibox can support for host name length
removeDomainName: "false"

# Image paths
images:
  # https://kubernetes-csi.github.io/docs/external-attacher.html
  attachersidecar: "registry.k8s.io/sig-storage/csi-attacher@sha256:033c2e5d3a190686c32298e0ae972a79aff903958db204a084c503356e66967d" # v4.4.1
  attachersidecar_pull_policy: "IfNotPresent"

  csidriver: "docker.io/infinidat/infinidat-csi-driver:v2.11.0"
  csidriver_pull_policy: "Always"

  # https://kubernetes-csi.github.io/docs/external-provisioner.html
  provisionersidecar: "registry.k8s.io/sig-storage/csi-provisioner@sha256:91c874488fbca39c6787a19b3e686836c29abcf069304064dba6bb9c9befb6e1" # v3.6.1
  provisionersidecar_pull_policy: "IfNotPresent"

  # https://kubernetes-csi.github.io/docs/node-driver-registrar.html
  registrarsidecar: "registry.k8s.io/sig-storage/csi-node-driver-registrar@sha256:cd21e19cd8bbd5bc56f1b4f1398a436e7897da2995d6d036c9729be3f4e456e6" # v2.9.0
  registrarsidecar_pull_policy: "IfNotPresent"

  # https://kubernetes-csi.github.io/docs/external-resizer.html
  resizersidecar: "registry.k8s.io/sig-storage/csi-resizer@sha256:f1f352df97874442624fcef23eab04aa038f66cb0e361212f6ec09e92998184d" # v1.9.0
  resizersidecar_pull_policy: "IfNotPresent"

  # https://kubernetes-csi.github.io/docs/external-snapshotter.html
  snapshottersidecar: "registry.k8s.io/sig-storage/csi-snapshotter@sha256:65c5ffde8fe6f68a2f19310cfd789befe7bdd16eedda219d9a0024f8fc68b802" # v6.3.1
  snapshottersidecar_pull_policy: "IfNotPresent"

  # https://kubernetes-csi.github.io/docs/livenessprobe.html
  livenesssidecar: "registry.k8s.io/sig-storage/livenessprobe@sha256:82adbebdf5d5a1f40f246aef8ddbee7f89dea190652aefe83336008e69f9a89f" # v2.11.0
  livenesssidecar_pull_policy: "IfNotPresent"

  #imagePullSecret: "private-docker-reg-secret"
Infinibox_Cred:
  - SecretName: "infinibox-creds"
    username: "someiboxusername"
    password: "someiboxpassword"
    hostname: "ibox0000"
    inbound_user: "iqn.2020-06.com.csi-driver-iscsi.infinidat:commonout"
    inbound_secret: "0.0000000000000"
    outbound_user: "iqn.2020-06.com.csi-driver-iscsi.infinidat:commonin"
    outbound_secret: "0.0000000000001"
