kind: Pod
apiVersion: v1
metadata:
  name: nfs-test
  namespace: infinidat-csi
  labels:
    security: s1
spec:
  imagePullSecrets:
  - name: $_E2E_IMAGE_PULL_SECRET
  containers:
    - name: csitest
      image: quay.io/quay/busybox
      volumeMounts:
      - mountPath: "/tmp/data"
        name: ibox-csi-volume
      command: [ "sleep", "1000" ]
  volumes:
    - name: ibox-csi-volume
      persistentVolumeClaim:
        claimName: nfs-pvc-rwx
