apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-rwx
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-nfs-rwx
  # volumeName: <<pv name>> #need to uncomment if want to use an existing pv
