apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: existing-treeq
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-treeq-retain
  volumeName: existing-treeq-pv
