kind: Pod
apiVersion: v1
metadata:
  name: existing-treeq-app
  namespace: infinidat-csi
spec:
  containers:
    - name: helloworld
      image: nginx:latest
      volumeMounts:
      - mountPath: "/tmp/data"
        name: ibox-csi-volume
  volumes:
    - name: ibox-csi-volume
      persistentVolumeClaim:
        claimName: existing-treeq
