apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: existing-treeq
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-treeq-storageclass-demo-retain
  volumeName: existing-treeq-pv
