apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: infinibox-csi-driver 
  name: existing-treeq-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    controllerExpandSecretRef:
      name: infinibox-creds
      namespace: infi
    controllerPublishSecretRef:
      name: infinibox-creds
      namespace: infi
    nodePublishSecretRef:
      name: infinibox-creds
      namespace: infi
    nodeStageSecretRef:
      name: infinibox-creds
      namespace: infi
    driver: infinibox-csi-driver
    volumeAttributes:
      ipAddress: 172.31.32.158
      storage_protocol: nfs_treeq
      volumePath: /csit_cc3681284b/other-treeq
    volumeHandle: 94199058#20009$$nfs_treeq
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ibox-treeq-storageclass-demo-retain
  volumeMode: Filesystem
  mountOptions:
    - hard
    - rsize=1048576
    - wsize=1048576
