apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $TEST_NAME
  namespace: $_E2E_NAMESPACE
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: $TEST_NAME
  # volumeName: <<pv name>> #need to uncomment if want to use an existing pv
