apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-rox-pvc
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-nfs-rox
  # volumeName: <<pv name>> #need to uncomment if want to use an existing pv
