apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rox
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  csi:
    controllerExpandSecretRef:
      name: infinibox-creds
      namespace: $_E2E_NAMESPACE
    controllerPublishSecretRef:
      name: infinibox-creds
      namespace: $_E2E_NAMESPACE
    driver: infinibox-csi-driver
    fsType: xfs
    nodePublishSecretRef:
      name: infinibox-creds
      namespace: $_E2E_NAMESPACE
    nodeStageSecretRef:
      name: infinibox-creds
      namespace: $_E2E_NAMESPACE
    nodeExpandSecretRef:
      name: infinibox-creds
      namespace: $_E2E_NAMESPACE
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1744639991471-2882-infinibox-csi-driver
      storage_protocol: fc
    volumeHandle: 2984318$$fc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ibox-fc-rox
  volumeMode: Filesystem
