apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fc-pvc-rox-readers
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-fc-rox
  volumeName: pv-rox
