kind: Pod
apiVersion: v1
metadata:
  name: fc-block-clone
  namespace: infinidat-csi
spec:
  imagePullSecrets:
  - name: private-docker-reg-secret
  containers:
    - name: csitest
      image: $_E2E_TEST_IMAGE
      volumeMounts:
      command: [ "csitestimage" ]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
      volumeMounts:
      - mountPath: "/tmp/csitesting"
        name: ibox-csi-volume
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: fc-block-pvc-clone
    - name: ibox-csi-volume
      emptyDir: {}
