apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: fc-block-pvc-clone
    namespace: $_E2E_NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  storageClassName: $TEST_NAME
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: $TEST_NAME
