apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: fc-block-pvc-clone
    namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  storageClassName: ibox-fc
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: fc-block-pvc
