apiVersion: csidriver.infinidat.com/v1
kind: Iboxpromote
metadata:
  annotations:
    infinidat.com/secret_name: infinibox-creds
    infinidat.com/secret_namespace: infinidat-csi
  name: iboxpromote-snapshot-test
spec:
  description: "test snapshot promote"  # user defined description
  entity_type: "SNAPSHOT"               # valid values: SNAPSHOT, KUBE_SNAPSHOT
  entity_name: "jeff-snapshot"    # the name of a snapshot to be promoted
  base_action: "NEW"                    # valid values: NEW
