kind: Pod
apiVersion: v1
metadata:
  name: nfs-anno-secret
  namespace: infinidat-csi
spec:
  imagePullSecrets:
  - name: private-docker-reg-secret
  containers:
    - name: csitest
      image: $_E2E_TEST_IMAGE
      volumeMounts:
      - mountPath: "/tmp/csitesting"
        name: ibox-csi-volume
      command: [ "csitestimage" ]
  volumes:
    - name: ibox-csi-volume
      persistentVolumeClaim:
        claimName: nfs-pvc-anno-secret
