# Default values for infinibox-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


namespace: infini

replicaCount: 1

instanceCount: 1

restBaseUrl: "https://172.17.35.61/"

infiniboxbinpath: /bin/infinibox

volumeNamePrefix: csi
storagePool: "iscsipool"
logLevel: "info"

# name of the driver 
#  note same name will be used for provisioner name
csiDriverName : "infinibox-csi-driver"

username: "dhanashreebiradar"
password: "Golang@123"

Infinibox:
  SecretName: infinibox-creds
  username: admin
  password: "123456"
  hosturl: 172.17.35.61

Infinibox2:
  SecretName: infinibox-creds2
  username: admin2
  password: "1234562"
  hosturl: 172.17.35.62


Initiator:
  SecretName: InitiatorSecretName
  username: admin
  password: "123456"


# Image paths 
images:
  # "images.attacher-sidercar" defines the container image used for the csi attacher sidecar
  attachersidecar: quay.io/k8scsi/csi-attacher:v2.1.0

  # "images.provisioner-sidercar" defines the container image used for the csi provisioner sidecar
  provisionersidecar: quay.io/k8scsi/csi-provisioner:v1.5.0

  # "images.snapshotter-sidercar" defines the container image used for the csi snapshotter sidercar
  snapshottersidecar: quay.io/k8scsi/csi-snapshotter:v1.2.2

  # "images.registrar-sidercar" defines the container images used for the csi registrar sidercar
  registrarsidecar: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0

  # "images.resizer-sidercar" defines the container image used for the csi provisioner sidecar
  resizersidecar: quay.io/k8scsi/csi-resizer:v0.3.0

  # "images.livenessprobe-sidercar" defines the container image used for the csi provisioner sidecar
  livenessprobesidecar: quay.io/k8scsi/livenessprobe:v1.1.0

  csidriver: docker.io/dhanashreebiradar/infinibox-csi-driver:test1

storageClass:
  name:
    fc: infiniboxcsidriver-fc
    iscsi:  infiniboxcsidriver-iscsi
    nfs:  infiniboxcsidriver-nfs

  # "storageClass.isDefault" defines whether the primary storage class should be the # default.
  isDefault: "true"

  # "storageClass.reclaimPolicy" defines what will happen when a volume is
  # removed from the Kubernetes API. Valid values are "Retain" and "Delete".
  reclaimPolicy: Delete
    
  fc: fc
  nfs: nfs
  iscsi: iscsi
