apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 11007
    protocol: TCP
    targetPort: 11007
    name: web
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
