{{ if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-tls-secret
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate | b64enc }}
  tls.key: {{ .Values.tls.privateKey | b64enc }}
{{ end }}
