---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-iboxcg-controller
rules:
- apiGroups:
  - csidriver.infinidat.com
  resources:
  - iboxcgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csidriver.infinidat.com
  resources:
  - iboxcgs/finalizers
  verbs:
  - update
- apiGroups:
  - csidriver.infinidat.com
  resources:
  - iboxcgs/status
  verbs:
  - get
  - patch
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-iboxcg-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-iboxcg-controller
  apiGroup: rbac.authorization.k8s.io
