{{- if not (empty .Values.Infinibox_Protocol_Secrets) }}
{{- $releaseNamespace := .Release.Namespace }}
  {{- range .Values.Infinibox_Protocol_Secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .SecretName }}
  namespace: {{ $releaseNamespace }}
  labels:
    app: infinidat-csi-driver-protocol-secret
type: Opaque
data:
  {{- if not (empty .preferred_auto_order) }}
  preferred_auto_order: "{{ .preferred_auto_order | b64enc }}"
  {{- end }}
  {{- if not (empty .storage_protocol) }}
  storage_protocol: "{{ .storage_protocol | b64enc }}"
  {{- end }}
  {{- if not (empty .nfs) }}
  {{- if not (empty .nfs.nfs_export_permissions) }}
  nfs.nfs_export_permissions: "{{ .nfs.nfs_export_permissions | b64enc }}"
  {{- end }}
  {{- if not (empty .nfs.network_space) }}
  nfs.network_space: "{{ .nfs.network_space | b64enc }}"
  {{- end }}
  {{- end }}
  {{- if not (empty .iscsi) }}
  {{- if not (empty .iscsi.network_space) }}
  iscsi.network_space: "{{ .iscsi.network_space | b64enc }}"
  {{- end }}
  {{- if not (empty .iscsi.useCHAP) }}
  iscsi.useCHAP: "{{ .iscsi.useCHAP | b64enc }}"
  {{- end }}
  {{- end }}
  {{- if not (empty .nvme) }}
  {{- if not (empty .nvme.network_space) }}
  nvme.network_space: "{{ .nvme.network_space | b64enc }}"
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
