{{- range  $key, $infisecrets := .Values.InfiniboxSecrets }}
{{ required "field required $infisecrets" $infisecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $infisecrets.SecretName }}-creds
  namespace: {{ $infisecrets.namespace }}
type: Opaque
data:
  username: "{{ $infisecrets.username }}"
  password: "{{ $infisecrets.password }}"
  hosturl:  "{{ $infisecrets.hosturl }}"
  name: 
  {{- if $infisecrets.chap }}
    node.session.auth.username: "{{ $infisecrets.username | b64enc }}"
    node.session.auth.password: "{{ $infisecrets.password | b64enc }}"
    node.session.auth.username_in: ""
    node.session.auth.password_in: ""
    node.sendtargets.auth.username: "{{ $infisecrets.username | b64enc }}"
    node.sendtargets.auth.password: "{{ $infisecrets.password | b64enc }}"
    node.sendtargets.auth.username_in: ""
    node.sendtargets.auth.password_in: ""
  {{ end }}
---
{{- end }}










#####################################################################3
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Infinibox.SecretName }}
  namespace: {{ .Release.NameSpace }}
type: Opaque
data:
  {{- if not (empty .Values.Infinibox.username) }}
  # set username to the base64 encoded user
  username: "{{ .Values.Infinibox.username | b64enc }}"
  {{ else }}
  username: {{ required "Username is required!" .Values.Infinibox.username }}
  {{- end }}
  {{- if not (empty .Values.Infinibox.password) }}
  # set password to the base64 encoded password
  password: "{{ .Values.Infinibox.password | b64enc }}"
  {{ else }}
  password: {{ required "Password is required!" .Values.Infinibox.password }}
  {{- end }}
  hosturl: "{{ .Values.Infinibox.hosturl | b64enc }}"
  node.session.auth.username: "{{ .Values.Infinibox.username | b64enc }}"
  node.session.auth.password: "{{ .Values.Infinibox.password | b64enc }}"
  node.session.auth.username_in: ""
  node.session.auth.password_in: ""
  node.sendtargets.auth.username: "{{ .Values.Infinibox.username | b64enc }}"
  node.sendtargets.auth.password: "{{ .Values.Infinibox.password | b64enc }}"
  node.sendtargets.auth.username_in: ""
  node.sendtargets.auth.password_in: ""
