apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-restore-from-snapshot-dnsname
  namespace: infinidat-csi
spec:
  storageClassName: ibox-dnsname-nfs
  dataSource:
    name: nfs-dnsname-snapshot
    kind: VolumeSnapshot
    apiGroup: "snapshot.storage.k8s.io"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

