apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: e2e-$_E2E_PROTOCOL-storageclass
provisioner: infinibox-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
# mountOptions: []
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: infinibox-creds
  csi.storage.k8s.io/controller-expand-secret-namespace: $_E2E_NAMESPACE
  csi.storage.k8s.io/controller-publish-secret-name: infinibox-creds
  csi.storage.k8s.io/controller-publish-secret-namespace:  $_E2E_NAMESPACE
  csi.storage.k8s.io/node-publish-secret-name: infinibox-creds
  csi.storage.k8s.io/node-publish-secret-namespace:  $_E2E_NAMESPACE
  csi.storage.k8s.io/node-stage-secret-name: infinibox-creds
  csi.storage.k8s.io/node-stage-secret-namespace:  $_E2E_NAMESPACE
  csi.storage.k8s.io/provisioner-secret-name: infinibox-creds
  csi.storage.k8s.io/provisioner-secret-namespace:  $_E2E_NAMESPACE
  csi.storage.k8s.io/fstype: ext4
  # gid: 1000 # GID of volume
  max_vols_per_host: "100"
  network_space: $_E2E_NETWORK_SPACE
  pool_name: $_E2E_POOL
  provision_type: "THIN"
  ssd_enabled: "false"
  storage_protocol: "iscsi"
  useCHAP: "none" # none / chap / mutual_chap
  # uid: 1000 # UID of volume
  # unix_permissions: 777 # chmod -R of volume
