apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: infinibox-csi-driver
  name: jeff-b3b8566819
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    controllerExpandSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    controllerPublishSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    driver: infinibox-csi-driver
    nodePublishSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    nodeStageSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    volumeAttributes:
      exportID: "450732"
      ipAddress: "172.31.32.158"
      network_space: "NAS"
      storage_protocol: nfs
      # uid: 1000
      # gid: 1000
      # unix_permissions: 777
      volPathd: /jeff-b3b8566819
    volumeHandle: 94953794$$nfs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ibox-nfs-retain
  volumeMode: Filesystem
  mountOptions:
    - hard
    - rsize=1048576
    - wsize=1048576
