apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-retain
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-nfs-retain
  volumeName: jeff-b3b8566819
