apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: cpvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
  storageClassName: infiniboxcsidriver-nfs-storageclass-test 
