apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infiniboxcsidriver-nfs-storageclass-test 
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: infiniboxcsidriver-nfs-storageclass-test 
 

