---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: csi-rbdplugin-snapclass
snapshotter: infinibox-csi-driver
parameters:
    pool_name: D_pool_1
    provision_type: THIN
    storage_protocol: nfs
    csi.storage.k8s.io/snapshotter-secret-name: infinibox-creds
    csi.storage.k8s.io/snapshotter-secret-namespace: infi
