kind: Pod
apiVersion: v1
metadata:
  name: ibox-pod-restore-snapshot-demo
  namespace: infinidat-csi
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/tmp/data"
        name: ibox-csi-volume
      command: [ "sleep", "1000" ]
  volumes:
    - name: ibox-csi-volume
      persistentVolumeClaim:
        claimName: ibox-snapshot-pvc-restore-demo
        
