apiVersion: v1
kind: Pod
metadata:
  name: pod-with-block-volume
  namespace: infinidat-csi
spec:
  imagePullSecrets:
  - name: $_E2E_IMAGE_PULL_SECRET
  containers:
    - name: fc-container
      image: quay.io/quay/busybox
      command: ["/bin/sh", "-c"]
      args: [ "tail -f /dev/null" ]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: block-pvc
        
