kind: Pod
apiVersion: v1
metadata:
  name: fc-test-using-clone
  namespace: infinidat-csi
spec:
  containers:
    - name: csitest
      image: infinidat/csitestimage:latest
      volumeMounts:
      - mountPath: "/tmp/csitesting"
        name: ibox-csi-volume
      command: [ "csitestimage" ]
  volumes:
    - name: ibox-csi-volume
      persistentVolumeClaim:
        claimName: fc-pvc-clone
