apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fc-pvc-fsg
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-fc-fsg
  #volumeName: <<pv name>> #need to uncomment if want to existing pv
