apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fc-pvc-restore-from-snapshot
  namespace: infinidat-csi
spec:
  storageClassName: ibox-fc
  dataSource:
    name: fc-snapshot
    kind: VolumeSnapshot
    apiGroup: "snapshot.storage.k8s.io"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

