apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
  namespace: infi
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-fc-storageclass-demo