apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Infinibox.SecretName }}
  namespace: {{ .Release.NameSpace }}
type: Opaque
data:
  {{- if not (empty .Values.Infinibox.username) }}
  # set username to the base64 encoded user
  username: "{{ .Values.Infinibox.username | b64enc }}"
  {{ else }}
  username: {{ required "Username is required!" .Values.Infinibox.username }}
  {{- end }}
  {{- if not (empty .Values.Infinibox.password) }}
  # set password to the base64 encoded password
  password: "{{ .Values.Infinibox.password | b64enc }}"
  {{ else }}
  password: {{ required "Password is required!" .Values.Infinibox.password }}
  {{- end }}
  hostip: "{{ .Values.Infinibox.apihost | b64enc }}"
