apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibox-treeq-storageclass-demo
provisioner: infinibox-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - hard
  - rsize=1048576
  - wsize=1048576
parameters: 
    pool_name: treeq_bug2
    network_space: nsnas
    provision_type: THIN
    storage_protocol: nfs_treeq
    fs_prefix: csit_
    nfs_export_permissions: "[{'access':'RW','client':'192.168.147.182-192.168.147.185','no_root_squash':true}]"
    ssd_enabled: "true"
    max_filesystems: "999"
    max_treeqs_per_filesystem: "20"
    max_filesystem_size: 30gib
    csi.storage.k8s.io/provisioner-secret-name: infinibox-creds
    csi.storage.k8s.io/provisioner-secret-namespace: infi
    csi.storage.k8s.io/controller-publish-secret-name: infinibox-creds
    csi.storage.k8s.io/controller-publish-secret-namespace: infi
    csi.storage.k8s.io/node-stage-secret-name: infinibox-creds
    csi.storage.k8s.io/node-stage-secret-namespace: infi
    csi.storage.k8s.io/node-publish-secret-name: infinibox-creds
    csi.storage.k8s.io/node-publish-secret-namespace: infi
    csi.storage.k8s.io/controller-expand-secret-name: infinibox-creds
    csi.storage.k8s.io/controller-expand-secret-namespace: infi
