apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvme-block-pvc-rwx
  namespace: $_E2E_NAMESPACE
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: nvme-block-rwx
