kind: Pod
apiVersion: v1
metadata:
  name: fc-block-node2
  namespace: infinidat-csi
spec:
  imagePullSecrets:
  - name: private-docker-reg-secret
  affinity:
    podAntiAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In 
            values:
            - s1
        topologyKey: kubernetes.io/hostname
  containers:
    - name: csitest
      image: $_E2E_TEST_BLOCK_IMAGE
      volumeMounts:
      command: [ "csitestimageblock" ]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
      env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: fc-block-pvc-rwx
