kind: Pod
apiVersion: v1
metadata:
  name: fc-block-node1
  namespace: infinidat-csi
  labels:
    security: s1
spec:
  imagePullSecrets:
  - name: $_E2E_IMAGE_PULL_SECRET
  containers:
    - name: csitest
      image: $_E2E_TEST_BLOCK_IMAGE
      volumeMounts:
      command: [ "csitestimageblock" ]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
      env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: fc-block-pvc-rwx
