apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fc-block-pvc-rwx
  namespace: infinidat-csi
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-fc-block-rwx
