apiVersion: v1
kind: Pod
metadata:
  name: pod-with-block-volume
  namespace: infi
spec:
  containers:
    - name: fc-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args: [ "tail -f /dev/null" ]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: block-pvc
        