
include ../Makefile-vars  # User configured vars
include Makefile-iscsi
# include Makefile-iscsi
# include Makefile-fc
# include Makefile-logging
# include ../Makefile-secrets
# include Makefile-testing-upstream-e2e
include ../Makefile-help

_purpose = The infindat-csi-driver-demo project demonstrates basic deployment and operatation of our CSI driver using a K3s cluster. Makefiles automate each step showing how this may be accomplished. See The README for details.
