apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
  namespace: infi
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibox-iscsi-storageclass-demo