apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ibox-snapshotclass-demo
  namespace: infi
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: infinibox-csi-driver
deletionPolicy: Delete
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: infinibox-creds
  csi.storage.k8s.io/snapshotter-secret-namespace: infi

