apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ibox-snapshotclass-demo-locking
  namespace: infinidat-csi
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: infinibox-csi-driver
deletionPolicy: Delete
parameters:
  lock_expires_at: "1 Hours"
  csi.storage.k8s.io/snapshotter-secret-name: infinibox-creds
  csi.storage.k8s.io/snapshotter-secret-namespace: infinidat-csi

