apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: iscsi-snapshot-locking
  namespace: infinidat-csi
spec:
  volumeSnapshotClassName: ibox-snapshotclass-locking
  source:
    persistentVolumeClaimName: iscsi-pvc
