apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ibox-pvc-snapshot-demo
  namespace: infi
spec:
  volumeSnapshotClassName: ibox-snapshotclass-demo
  source:
    persistentVolumeClaimName: ibox-pvc-demo

