apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-rox-pv-from-existing
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  csi:
    controllerExpandSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    controllerPublishSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    driver: infinibox-csi-driver
    fsType: xfs
    nodePublishSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    nodeStageSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    volumeAttributes:
      iqn: iqn.2009-11.com.infinidat:storage:infinibox-sn-1111
      portals: 1.2.4.1,1.2.4.7,1.1.4.8
      readOnly: "false"
      network_space: "iSCSI"
      storage.kubernetes.io/csiProvisionerIdentity: 1111111111111-3054-infinibox-csi-driver
      storage_protocol: iscsi
      uid: "3000"
      gid: "3000"
      # unix_permissions: 777
      useCHAP: none
    volumeHandle: 1233762$$iscsi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ibox-iscsi-rox-readers
  volumeMode: Block
