apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-block-pvc
  namespace: infinidat-csi
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-iscsi-rox-block
