apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibox-iscsi-rox-block
provisioner: infinibox-csi-driver
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
# mountOptions: []
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: infinibox-creds
  csi.storage.k8s.io/controller-expand-secret-namespace: infinidat-csi
  csi.storage.k8s.io/controller-publish-secret-name: infinibox-creds
  csi.storage.k8s.io/controller-publish-secret-namespace: infinidat-csi
  csi.storage.k8s.io/node-publish-secret-name: infinibox-creds
  csi.storage.k8s.io/node-publish-secret-namespace: infinidat-csi
  csi.storage.k8s.io/node-stage-secret-name: infinibox-creds
  csi.storage.k8s.io/node-stage-secret-namespace: infinidat-csi
  csi.storage.k8s.io/provisioner-secret-name: infinibox-creds
  csi.storage.k8s.io/provisioner-secret-namespace: infinidat-csi
  csi.storage.k8s.io/fstype: xfs
  network_space: "iSCSI"
  pool_name: "csitesting"
  storage_protocol: "iscsi"
  useCHAP: "none" # none / chap / mutual_chap
  # optional parameters
  #max_vols_per_host: "100"
  #provision_type: "THIN"
  #ssd_enabled: "false"
  uid: "3000" # UID of volume
  gid: "3000" # GID of volume
  #unix_permissions: "777" # optional volume mount permissions
