apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: ibox-pvc-clone-snapshot-demo
  namespace: infi
spec:
  snapshotClassName: ibox-snapshotclass-demo
  source:
    name: ibox-pvc-clone-demo
    kind: PersistentVolumeClaim

