apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-infinibox-storageclas-nfs
