apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: csi-driver-data-replicaset
  labels:
    app: nginx-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-service
  template:
    metadata:
      labels:
        app: nginx-service
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/data
              name: csi-driver-data
      volumes:
        - name: csi-driver-data
          persistentVolumeClaim:
            claimName: ibox-pvc-demo
