apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibox-snapshot-pvc-restore-demo-5
  namespace: infi
spec:
  storageClassName: ibox-nfs-storageclass-demo
  dataSource:
    name: ibox-pvc-snapshot-demo-2
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: restorepvc
#   namespace: test
# spec:
#   storageClassName: vxflexos
#   dataSource:
#     name: pvol0-snap1
#     kind: VolumeSnapshot
#     apiGroup: snapshot.storage.k8s.io
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
