apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-infinibox-storageclas-nfs
provisioner: infinibox-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
