apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    controllerExpandSecretRef:
      name: $_E2E_IBOX_SECRET
      namespace: $_E2E_NAMESPACE
    controllerPublishSecretRef:
      name: $_E2E_IBOX_SECRET
      namespace: $_E2E_NAMESPACE
    driver: infinibox-csi-driver
    fsType: ext4
    nodePublishSecretRef:
      name: $_E2E_IBOX_SECRET
      namespace: $_E2E_NAMESPACE
    nodeStageSecretRef:
      name: $_E2E_IBOX_SECRET
      namespace: $_E2E_NAMESPACE
    nodeExpandSecretRef:
      name: $_E2E_IBOX_SECRET
      namespace: $_E2E_NAMESPACE
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1731709114360-6181-infinibox-csi-driver
      storage_protocol: fc
    volumeHandle: 2922271$$fc
  persistentVolumeReclaimPolicy: Delete
  storageClassName: $TEST_NAME
  volumeMode: Filesystem
