apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-replica-fs
  namespace: $_E2E_NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-replica-fs
  #volumeName: <<pv name>> #need to uncomment if want to existing pv
