kind: Pod
apiVersion: v1
metadata:
  name: ibox-pod-tree1-demo
  namespace: infi
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/tmp/data"
        name: ibox-csi-volume      
  volumes:
    - name: ibox-csi-volume
      persistentVolumeClaim:
        claimName: ibox-tree-pvc-demo
