apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibox-tree-pvc-demo-1
  namespace: infi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibox-tree-storageclass-demo
 

