apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibox-tree-pvc-demo-2
  namespace: infi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ibox-tree-storageclass-demo
 

