apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infiniboxcsidrivers.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: InfiniboxCsiDriver
    listKind: InfiniboxCsiDriverList
    plural: infiniboxcsidrivers
    singular: infiniboxcsidriver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
