apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: infinibox-csi-driver 
  name: user1-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    controllerExpandSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    controllerPublishSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    nodePublishSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    nodeStageSecretRef:
      name: infinibox-creds
      namespace: infinidat-csi
    driver: infinibox-csi-driver
    volumeAttributes:
      ipAddress: 172.31.32.158
      storage_protocol: nfs_treeq
      volumePath: /treeq-filesystem-test/user1
    volumeHandle: 98125215#996697$$nfs_treeq
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ibox-treeq-admin
  volumeMode: Filesystem
  mountOptions:
    - hard
    - rsize=1048576
    - wsize=1048576
