apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user2-pvc
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-treeq-admin
  volumeName: user2-pv
