apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-fsg
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-nfs-fsg
  # volumeName: <<pv name>> #need to uncomment if want to use an existing pv
