apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibox-nfs-fsg
provisioner: infinibox-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions: # optional: defaults shown below, be sure to include vers=3 if you override
  - vers=3
  - tcp
  - rsize=262144
  - wsize=262144
parameters:
    # reference secret with InfiniBox credentials
    csi.storage.k8s.io/controller-expand-secret-name: infinibox-creds
    csi.storage.k8s.io/controller-expand-secret-namespace: infinidat-csi
    csi.storage.k8s.io/controller-publish-secret-name: infinibox-creds
    csi.storage.k8s.io/controller-publish-secret-namespace: infinidat-csi
    csi.storage.k8s.io/node-publish-secret-name: infinibox-creds
    csi.storage.k8s.io/node-publish-secret-namespace: infinidat-csi
    csi.storage.k8s.io/node-stage-secret-name: infinibox-creds
    csi.storage.k8s.io/node-stage-secret-namespace: infinidat-csi
    csi.storage.k8s.io/provisioner-secret-name: infinibox-creds
    csi.storage.k8s.io/provisioner-secret-namespace: infinidat-csi

    # InfiniBox configuration
    storage_protocol: nfs
    fstype: ext4        # fstype required when fsGroup is in pod spec  
    network_space: NAS # InfiniBox network space name
    pool_name: csitesting # InfiniBox pool name

    # optional parameters
    #provision_type: THIN
    #ssd_enabled: "true"
    snapdir_visible: "true"   # optional: specify whether .snapshot directory is visible
    # NOTE:  uid, guid, unix_permissions parameters require no_root_squash to be true!
    uid: "2000"               # optional: override default UID for filesystem mount, ignored when fsgroup in pod
    gid: "2000"               # optional: override default GID for filesystem mount, ignored when fsgroup in pod
    unix_permissions: "777"   # optional: override default permissions for filesystem mount, ignored for fsgroup
    # privileged_ports_only: no # optional: force use of  privileged ports only
    # 
    # nfs_export_permissions : "[{'access':'RW','client':'192.168.147.190-192.168.147.199','no_root_squash':true}]" # ip address range example
    nfs_export_permissions : "[{'access':'RW','client':'*','no_root_squash':true}]" # wildcard example
