kind: Pod
apiVersion: v1
metadata:
  name: nvme-test-rox-reader
  namespace: $_E2E_NAMESPACE
spec:
  imagePullSecrets:
  - name: private-docker-reg-secret
  securityContext:
    seLinuxOptions:
      type: "spc_t"
  containers:
    - name: csitest
      image: git.infinidat.com:4567/host-opensource/$_E2E_NAMESPACE-driver/csitestimage:latest
      env:
      - name: READ_ONLY
        value: "true"
      volumeMounts:
      - mountPath: "/tmp/csitesting"
        name: ibox-csi-volume
      command: [ "csitestimage" ]
  volumes:
    - name: ibox-csi-volume
      persistentVolumeClaim:
        claimName: nvme-pvc-rox-readers
