apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc-anno
  namespace: infinidat-csi
  annotations:
    infinidat.com/network_space: iSCSI
    infinidat.com/pool_name: csitesting
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-iscsi-anno
  #volumeName: <<pv name>> #need to uncomment if want to existing pv
