apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc-restore-from-snapshot-anno
  namespace: infinidat-csi
spec:
  storageClassName: ibox-iscsi-anno
  dataSource:
    name: iscsi-snapshot-anno
    kind: VolumeSnapshot
    apiGroup: "snapshot.storage.k8s.io"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

