apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-ro-pvc-from-existing-pv
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-iscsi-ro
  volumeName: ro-pv-from-existing
