apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-ro-pvc
  namespace: infinidat-csi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibox-iscsi-ro
  # volumeName: <<pv name>> #need to uncomment if want to use an existing pv
